/* tslint:disable */
/* eslint-disable */
/**
 * The Maritime Resource Registry API
 * The Maritime Resource Registry can be used to create and query resources that are identified by an MRN
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Representation of the contact information of an owner of a namespace or an MRR
 * @export
 * @interface OwnerDTO
 */
export interface OwnerDTO {
    /**
     * The name of the owner
     * @type {string}
     * @memberof OwnerDTO
     */
    name?: string;
    /**
     * The mail for the point of contact of the owner
     * @type {string}
     * @memberof OwnerDTO
     */
    email?: string;
    /**
     * The phone number for the point of contact of the owner
     * @type {string}
     * @memberof OwnerDTO
     */
    phone?: string;
    /**
     * The URL for the website of the owner
     * @type {string}
     * @memberof OwnerDTO
     */
    url?: string;
    /**
     * The address of the owner
     * @type {string}
     * @memberof OwnerDTO
     */
    address?: string;
    /**
     * The country of the owner
     * @type {string}
     * @memberof OwnerDTO
     */
    country?: string;
}
