/* tslint:disable */
/* eslint-disable */
/**
 * The Maritime Resource Registry API
 * The Maritime Resource Registry can be used to create and query resources that are identified by an MRN
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NamespaceSyntaxDTO } from './namespace-syntax-dto';
import { PageableObject } from './pageable-object';
import { SortObject } from './sort-object';
/**
 * 
 * @export
 * @interface PageNamespaceSyntaxDTO
 */
export interface PageNamespaceSyntaxDTO {
    /**
     * 
     * @type {number}
     * @memberof PageNamespaceSyntaxDTO
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageNamespaceSyntaxDTO
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageNamespaceSyntaxDTO
     */
    size?: number;
    /**
     * 
     * @type {Array<NamespaceSyntaxDTO>}
     * @memberof PageNamespaceSyntaxDTO
     */
    content?: Array<NamespaceSyntaxDTO>;
    /**
     * 
     * @type {number}
     * @memberof PageNamespaceSyntaxDTO
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageNamespaceSyntaxDTO
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageNamespaceSyntaxDTO
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageNamespaceSyntaxDTO
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageNamespaceSyntaxDTO
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageNamespaceSyntaxDTO
     */
    last?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageNamespaceSyntaxDTO
     */
    empty?: boolean;
}
