/* tslint:disable */
/* eslint-disable */
/**
 * The Maritime Resource Registry API
 * The Maritime Resource Registry can be used to create and query resources that are identified by an MRN
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MaritimeResourceDTO } from './maritime-resource-dto';
import { PageableObject } from './pageable-object';
import { Sort } from './sort';
/**
 * 
 * @export
 * @interface PageMaritimeResourceDTO
 */
export interface PageMaritimeResourceDTO {
    /**
     * 
     * @type {number}
     * @memberof PageMaritimeResourceDTO
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMaritimeResourceDTO
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMaritimeResourceDTO
     */
    size?: number;
    /**
     * 
     * @type {Array<MaritimeResourceDTO>}
     * @memberof PageMaritimeResourceDTO
     */
    content?: Array<MaritimeResourceDTO>;
    /**
     * 
     * @type {number}
     * @memberof PageMaritimeResourceDTO
     */
    number?: number;
    /**
     * 
     * @type {Sort}
     * @memberof PageMaritimeResourceDTO
     */
    sort?: Sort;
    /**
     * 
     * @type {number}
     * @memberof PageMaritimeResourceDTO
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageMaritimeResourceDTO
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageMaritimeResourceDTO
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageMaritimeResourceDTO
     */
    last?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageMaritimeResourceDTO
     */
    empty?: boolean;
}
