/* tslint:disable */
/* eslint-disable */
/**
 * The Maritime Resource Registry API
 * The Maritime Resource Registry can be used to create and query resources that are identified by an MRN
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OwnerDTO } from './owner-dto';
/**
 * Object that holds the necessary information for registering an MRN namespace syntax
 * @export
 * @interface SyntaxCreationDTO
 */
export interface SyntaxCreationDTO {
    /**
     * The MRN namespace that the syntax describes
     * @type {string}
     * @memberof SyntaxCreationDTO
     */
    namespace?: string;
    /**
     * The parent MRN namespace that the syntax is a subset of
     * @type {string}
     * @memberof SyntaxCreationDTO
     */
    parentNamespace?: string;
    /**
     * The ABNF syntax of the MRN namespace
     * @type {string}
     * @memberof SyntaxCreationDTO
     */
    abnfSyntax?: string;
    /**
     * 
     * @type {OwnerDTO}
     * @memberof SyntaxCreationDTO
     */
    namespaceOwner?: OwnerDTO;
}
